Vagrant.configure("2") do |config|
  # Usando a box Ubuntu 20.04
  config.vm.box = "ubuntu/focal64"
  
  # Definindo o nome da máquina
  config.vm.hostname = "wordpress-app01"
  
  # Port forwarding para acessar a aplicação na porta 8080 da VM
  config.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8008  # Porta para aplicação web

  # Configuração de adaptador de rede em modo bridged, usando enp2s0 e IP estático
  config.vm.network "public_network", bridge: "enp2s0", type: "static", ip: "192.168.98.40", netmask: "255.255.255.0", gateway: "192.168.98.1"

  # Configurações de memória e CPUs
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4098"
    vb.cpus = 2        
  end
end
