Vagrant.configure("2") do |config|
  # Usando a box Ubuntu 20.04
  config.vm.box = "ubuntu/focal64"
  
  # Definindo o nome da máquina
  config.vm.hostname = "ubuntu-20-04-vm"
  
  # Port forwarding para acessar a aplicação na porta 8080 da VM
  config.vm.network "forwarded_port", guest: 22, host: 2223, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 8082  # Porta para aplicação web

  # Configuração de adaptador de rede em modo bridged, usando enp2s0 e IP estático
  config.vm.network "public_network", bridge: "enp2s0", type: "static", ip: "192.168.98.41", netmask: "255.255.255.0", gateway: "192.168.98.1"

  # Configurações de memória e CPUs
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2        
  end

  # Provisionamento para adicionar a chave pública ao arquivo authorized_keys
  config.vm.provision "shell", inline: <<-SHELL
    # Criar o diretório .ssh se não existir
    mkdir -p /home/vagrant/.ssh

    # Adicionar a chave pública SSH ao arquivo authorized_keys
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDiFqy4Lhfscx28yAToiVTRd67MLYpQYfYSGhK2cYmR981OLi6dQUJ5kG3huPdAxUi2Wfe7IH2b1Zgs4n4O9xxUgNhguF36BRZ146awP3hwPmnFs6dr2N8IFRBppq/VeFXh+fCtpJU1+PcD3iG0YmY1eqbu8EE317fGGENnQIBEHDkXgsvwo3DmM7u5oqqcC8ajm85KAM7xt/AIlycSC1i4kzxAbDYz4CsvUn2HTOfr8F6S9QLKGESf3VeN8wxzN6vJLt2LY13DnIRNjRbb4momsN6ce3KpEbyzbeZXpANTvgSwKyMqiegbLjULbi7Ste1GHMOcbuxurQM/e5rBBa8QJSjnHmMRUaKTxv4DNyKD8WWgYVMxcZpgV8t+E1r1+jGOb+EQ12ThDiBs5ON04RMuviv/ktfUrTSH7ens/3VruoYtvjUYAsUM3or2H156o5to7Z9fHq5o0q9lWZ1S1o3EPq6Qe+QwZWCcu6zkY93WXNVVtQS+QauEXGxqS537QoAjmjkV0UYLG7EEndi0W/bHxBKVxRagusRQL3LCe/ONUNv+WzdR4LXNtKwMOHBRdAgYWjExp0CPJSanA5lQqNEnI/cyHYbuC67RnIaKI8A0/zqejEnsPtF+7HPwXZA+it0cF7CXuLR6KYTJA1TOAsgoPQyYRDhzjy0nfITP7U7f0Q== brunosantosc1@gmail.com" >> /home/vagrant/.ssh/authorized_keys

    # Corrigir as permissões do diretório e arquivo .ssh
    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL
end
