---
  - name: Instalacao nginx e php para o funcionamento do WP
    dnf:
      name:
        - nginx
        - unzip
        - php
        - php-fpm
        - php-mysqlnd
        - php-gd
        - php-curl
        - php-mbstring
        - php-xml
        - php-zip
        - php-bcmath
        - php-json
      state: present

  - name: Criando diretorio web
    file:
      path: /var/www/html
      state: directory
      mode: '0755'

  - name: Iniciando e habilitando php-fpm
    service:
      name: php-fpm
      state: started
      enabled: yes

  - name: Configuracao do vhost nginx
    template:
      src: vhost.nginx.conf.j2
      dest: /etc/nginx/conf.d/wordpress.conf

  - name: Removendo config padrao do nginx
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: Baixando o projeto do wordpress e descompactando
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      remote_src: yes

  - name: Alterando o arquivo wp-config
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: Alterando permissao da pasta /var/www/html/wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: nginx
      group: nginx
      recurse: yes
      mode: '0755'

  - name: Restarting nginx
    service:
      name: nginx
      state: restarted
      enabled: yes
