version: '3.3'

services:
  vault:
    image: hashicorp/vault:1.15.2
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
    volumes:
      - vault-data:/vault/file

volumes:
  vault-data:
    driver: local
